# Generated by Django 6.0.1 on 2026-03-03 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2026, 3, 3)),
            preserve_default=False,
        ),
    ]
